apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-configmap
data:
  eureka_server_address: http://registry-0.eureka-naming-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-naming-server #headless service name
  labels:
    app: registry
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka-port
  selector:
    app: registry # select stateful set
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry # Statefulset name
spec:
  serviceName: "eureka-naming-server" # Headless service name
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: eureka-container
          image: adpham1302/eureka-naming-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-configmap
                  key: eureka_server_address
---
# Pods fixed registry
apiVersion: v1
kind: Service
metadata:
  name: eureka-pods-fixed
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761