server:
  port: 9090

spring:
  application:
    name: status-ms
  zipkin:
    base-url: http://zipkin:9411
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Anhdung1302
    url: jdbc:mysql://mysql:3306/spcloud?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-naming-server:8761/eureka
    enabled: true
    fetch-registry: true
    register-with-eureka: true

