server:
  port: 8080

spring:
  application:
    name: student-ms
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Anhdung1302
    url: jdbc:mysql://localhost:3306/spcloud?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    fetch-registry: true
    register-with-eureka: true
