server:
  port: 8080

spring:
  application:
    name: student-ms
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Anhdung1302
    url: jdbc:mysql://mysql:3306/spcloud?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-0.eureka-naming-server.default.svc.cluster.local:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: registry-0
